WIP: Add repo meta files
WordPress/wordcamp.org pull request #2
Opened 2018-11-16 18:54 UTC by coreymckrill

Add GitHub's recognized meta files

- [ ] Readme
- [ ] License
- [ ] Contributing
- [ ] Code of Conduct
- [ ] Issue template

2018-11-16 19:21 UTC, iandunn commented
We'd need to add these to `meta.svn` in order for them to be synced, so I wonder if it'd be better to wait until we switch to Git natively?

Alternatively, we could add them to `meta.svn`, but make them generic enough to cover GitHub and Trac.

If we do that, it might be nice to use `.github/CONTRIBUTING.md` to keep things organized, since there are probably other GitHub templates we might want to add. e.g., https://github.com/WordPress/gutenberg/tree/480016dd1833728f9028a0235dc4ebe28393f303/.github


I see this repo more as a temporary things for early-stage collaboration on large new features like the blocks, rather than something for contributors, which should still use instead of Trac for the time being. Maybe we could setup some automation etc that would make it useful for all contributions, though? Let me know what y'all think.

2018-11-20 11:58 UTC, vedanshujain commented
> I see this repo more as a temporary things for early-stage collaboration on large new features like the blocks, rather than something for contributors, which should still use instead of Trac for the time being. 

While we still use Trac for time being, lets also move (slowly) towards making this repo our main hub for contributors as well. To that end, its probably a good idea to add git specific repo meta files in `meta.svn` as well (maybe mentioning that this is intended for our GitHub repo with link).

Also, specifically what automatons you have in mind that we can setup.

2019-05-06 16:54 UTC, iandunn requested changes
Some changes needed, and I think we'll need to revamp this in light of #113 too

2019-05-06 16:54 UTC, iandunn commented on CONTRIBUTING.md
> +Thanks for contributing to WordCamp.org! This page will explain all the ways you can contribute.
`SHOULD` - We can maybe just link to the existing Handbook page, to keep things DRY.

2019-05-06 16:54 UTC, iandunn commented on LICENSE.txt
> +This program is free software; you can redistribute it and/or modify
`MIGHT` - IIRC, we're _technically_ supposed to have the full file, but it feels much cleaner to just make the `License` section of the `README` link to https://www.gnu.org/licenses/old-licenses/gpl-2.0.html? That feels much cleaner.

IIRC, GitHub also has something where you can mark the license, and it'll show up in GH's interface somewhere.

2019-05-06 16:54 UTC, iandunn commented on readme.md
> +This is a mirror of the [WordCamp directory](https://meta.svn.wordpress.org/sites/trunk/wordcamp.org/) from the WordPress Meta SVN repository, though it does not include externals.
`SHOULD` - maybe link to the Meta Environment provision for details on getting those? Or maybe #113 will include instructions for Docker instead.

2019-05-06 16:54 UTC, iandunn commented on readme.md
> +WordCamp.org is a WordPress multisite network that supports WordCamp events around the world.
```suggestion
[WordCamp.org](https://central.wordcamp.org) is a WordPress multisite network that supports WordCamp events around the world.
```

2019-05-06 16:54 UTC, iandunn commented on readme.md
> +This is a mirror of the [WordCamp directory](https://meta.svn.wordpress.org/sites/trunk/wordcamp.org/) from the WordPress Meta SVN repository, though it does not include externals.
`SHOULD` - We'll need to update this soon to reflect that it won't be a mirror.

2019-05-06 16:54 UTC, iandunn commented on CONTRIBUTING.md
> +Thanks for contributing to WordCamp.org! This page will explain all the ways you can contribute.
`SHOULD` - I think this should live in `.github/` to avoid cluttering the root, and since we'll probably want to add issue templates, etc.

2019-07-04 18:41 UTC, closed without merging

2019-07-04 18:42 UTC, iandunn commented
d339420 covers a lot of what we'll want here, but doesn't add contributing templates, etc. We can open new PRs for anything else we still want to add.